apiVersion: v2
name: operator
description: Local chart to install the operator
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: atlas-operator
    version: "0.6.4"
    repository: "oci://ghcr.io/ariga/charts"
