apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  name: appmigration
spec:
  cloud:
    tokenFrom:
      secretKeyRef:
        key: ATLAS_TOKEN
        name: atlas-token
  protectedFlows:
    migrateDown:
      allow: true
  urlFrom:
    secretKeyRef:
      key: url
      name: postgres-credentials
  dir:
    remote:
      name: atlas-argo-demo
      tag: 2ab4700937c1c0e09e4f2d56586545fb333db8df
