apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rotemtam/atlas-argo-demo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true